### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by ndvbd** [barcavia/RealTime-DeepfakeDetection-in-the-RealWorld#1]
Hi,
1. How much memory is required to train it?
2. Do you publish the already-trained detector?
3. How much memory does the detector need in inference?

**Comment by barcavia** [comment]
Hi,
Yes, I publish the already-trained detectors. you can see how to use it in the README file of the repository.
As stated in the paper, to train LaDeDa, we used a single NVIDIA RTX A5000 (21g). for inference, it depends on the dataset you wish to use, but the weights can be loaded on your CPU.
