### ISSUE TITLE
preprocess_type in LaDeDa model

### ISSUE THREAD

**Issue by fabrizioguillaro** [barcavia/RealTime-DeepfakeDetection-in-the-RealWorld#2]
Hi, the code will not run because in the declaration of LaDeDa model, a mandatory parameter "preprocess_type" is required, but it does not have a default value assigned.
Which one is the value that you used? "raw",  "NPR", "x_grad", "y_grad", "left_diag", "right_diag"?

**Comment by barcavia** [comment]
Hi,
I see what you mean regarding the declaration, but it actually does have a default value:
parser.add_argument('--preprocess', type=str, default="NPR", help='image preprocess type used')
you can find it in the base_options.py file.

I fixed the issue :)
