### ISSUE TITLE
Errors when running test.py

### ISSUE THREAD

**Issue by jonasricker** [barcavia/RealTime-DeepfakeDetection-in-the-RealWorld#4]
Thank you for providing the code alongside your paper! I want to test you method, but when I try to run test.py I encounter several errors, e.g., the module `util` cannot be imported, `opt` is not defined, and more. Could it be that this is not the most recent version of the script?

**Comment by barcavia** [comment]
Hi :)
The issues have fixed (the util file is just in case you want to use logging, and the opt was the Testopt, which already exists in the file).

**Comment by jonasricker** [comment]
Thanks for the quick reply. I still needed to make some changes to get test.py running. I created a pull request (#5) with all the changes required to reproduce the results for the ForenSynths dataset (LaDeDa and Tiny). I also incorporated the fix mentioned in #3, however I noticed that this is only required for LaDeDa, not for Tiny. With these changes I'm able to get the same results as in Table 2.
